services:
  traefik:
    image: traefik:${VERSION_T:-latest}
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${FORWARD_PORT_HTTP:-80}:80"       # Для перенаправления HTTP -> HTTPS
      - "${FORWARD_PORT_HTTPS:-443}:443"     # Внешний защищенный порт для входа в Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certificates:/letsencrypt
    command:
      #- "--log.level=DEBUG"       # <--- ТЕПЕРЬ ОН БУДЕТ ПИСАТЬ ВСЁ
      #- "--log.format=common"     # Обычный текстовый формат логов

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Strict connect to portainer_bridge_network network
      - "--providers.docker.network=portainer_bridge_network"
      # Open port 80
      - "--entrypoints.web.address=:80"
      # Open port 443
      - "--entrypoints.websecure.address=:443"
      # Redirections with 80 to 443
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Настройка резолвера (он просто готов к работе, но не включится без флага CERT_RESOLVER в labels)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-admin@localhost.local}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - bridge_network

  portainer:
    image: portainer/portainer-ce:${VERSION_P:-latest}
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_volume:/data
    environment:
      - TZ=UTC
      - DO_NOT_TRACK=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=portainer_bridge_network"

      - "traefik.http.routers.portainer.rule=Host(`192.168.100.180`)"
      #- "traefik.http.routers.portainer.rule=Host(`${DOMAIN:-portainer.local}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      # самоподписанный SSL
      - "traefik.http.routers.portainer.tls=true"
      # Local port in container portainer
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      # Если в .env переменная CERT_RESOLVER пустая — Traefik выдаст локальный самоподписанный SSL.
      # Если указано CERT_RESOLVER=myresolver — включится Let's Encrypt.
      - "traefik.http.routers.portainer-https.tls.certresolver=${CERT_RESOLVER:-}"
      - "traefik.http.routers.portainer-https.tls=true"
    networks:
      - bridge_network

volumes:
  portainer_data_volume:
    name: portainer_data_volume
  traefik_certificates:
    name: traefik_certificates

networks:
  bridge_network:
    name: portainer_bridge_network
    driver: bridge